permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

on:
  workflow_dispatch:
    inputs:
      rg-name:
        type: string
        description: 'Resource Group Name'
        required: true
      rg-region:
        type: choice
        description: 'Resource Group Region'
        required: true
        default: 'japaneast'
        options:
          - 'japaneast'
          - 'japanwest'
      owner:
        type: string
        description: 'Owner UPN'
        required: true
      department:
        type: string
        description: 'Department'
        required: true



jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          branch: ${{ github.ref_name }}

      - name: 'install az cli extension for blueprint'
        run: |
          az extension add --name blueprint
      - name: 'create security gorup of resource group owner'
        run: |
          # オーナーグループの作成
          GROUP_ID=$(az ad group create --display-name ${{ github.event.inputs.rg-name }}-owner --mail-nickname ${{ github.event.inputs.rg-name }}-owner --query id -o tsv)
          # オーナーユーザーのObjectIDを取得
          OWNER_ID=$(az ad user show --id ${{ github.event.inputs.owner }} --query id -o tsv)
          # オーナーグループにオーナーユーザーを追加
          az ad group member add --group $GROUP_ID --member-id $OWNER_ID
          # GROUP_IDを環境変数にセット
          echo "GROUP_ID=$GROUP_ID" >> $GITHUB_ENV

      - name: 'create parameters file'
        run: |
          # ブループリントのパラメータファイルを作成
          echo "{
            \"rgName\": {
              \"value\": \"${{ github.event.inputs.rg-name }}\"
            },
            \"[ユーザー名またはアプリケーション名]:所有者_RoleAssignmentName\": {
              \"value\": [
                \"${GROUP_ID}\"
              ]
            },
            \"タグとその値のリソースグループへの追加_tagValue\": {
              \"value\": \"${{ github.event.inputs.department }}\"
            }
          }" > parameters.json

      - name: 'create blueprint assignment'
        run: |
          # ブループリントの割り当て
          #
          az blueprint assignment create --name assignment-${{ github.event.inputs.rg-name }} --subscription ${{ secrets.SUBSCRIPTION_ID }} --identity-type SystemAssigned --location ${{ github.event.inputs.rg-region }} --resource-group-value artifact_name=sandbox-rg location=
          ${{ github.event.inputs.rg-region }} name=test2-rg --parameters ./parameters.json --blueprint-version /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/providers/Microsoft.Blueprint/blueprints/SandboxBluePrint